import cohere
from dotenv import load_dotenv
import os
import json

# Load environment variables
load_dotenv()

COHERE_API_KEY = os.getenv("COHERE_API_KEY")


def get_cohere_response(customer_json):
    """
    Takes a JSON string representing customer financial data
    and generates feedback using Cohere's API.

    Args:
        customer_json (str): A JSON string of customer financial data.

    Returns:
        str: Feedback generated by Cohere's API.
    """
    # Initialize the Cohere client
    co = cohere.Client(COHERE_API_KEY)

    # Define the prompt
    prompt = (
        f"{customer_json} Here is the JSON for a person's financial data. "
        "Provide short feedback to the user about their finances."
    )

    try:
        # Generate a response using Cohere's command model
        response = co.generate(
            model="command-xlarge-2023-01",  # Use the appropriate Cohere model
            prompt=prompt,
            max_tokens=150,  # Limit the response length
            temperature=0.7,  # Adjust for more/less creative output
        )

        # Extract the generated text
        generated_text = response.generations[0].text.strip()
        return generated_text

    except Exception as e:
        print(f"Error while calling Cohere API: {e}")
        return None


# Example data for testing
data = {
    "mortgageApplication": {
        "applicant": {
            "annualIncome": 85000,
            "dateOfBirth": "1985-03-10",
            "employmentStatus": "Employed",
            "fullName": "Alice Johnson",
            "ssn": "123-45-6789"
        },
        "applicationStatus": "Pending",
        "creditScore": 720,
        "loanTerms": {
            "interestRate": 3.5,
            "loanTermYears": 30,
            "monthlyPayment": 1078
        },
        "propertyDetails": {
            "address": "123 Elm Street, Springfield, IL",
            "downPayment": 60000,
            "loanAmount": 240000,
            "propertyValue": 300000
        }
    }
}

# Convert the data to a JSON string
customer_json = json.dumps(data, indent=2)

# Get Cohere response
feedback = get_cohere_response(customer_json)

# Print the feedback
if feedback:
    print("Feedback:", feedback)
else:
    print("Failed to generate feedback.")
